fix shrinks1
currently, specifying --shrinks1 causes error
  File "/home/kaelber/EMAN2/bin/e2refinemulti.py", line 595, in main
    shrinks1=shrinks1,shrink=shrink,prefilt=prefilt,simmask=simmask,verbose=verbose,parallel=parallel)
UnboundLocalError: local variable 'shrinks1' referenced before assignment
This is because the variable shrinks1 is only created if options.shrinks1==0 (the default) since the author forgot to define shrinks1 in an else condition. I tested the proposed change on sphere and it works.